resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: 1.17
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/katochm/microservices-demo.git
    branch: master
    private_key: ((github_private_key))
    path: src/adservice/

- name: docker-hub
  type: docker-image
  source:
    repository: katochm/adservice
    tag: latest
    username: ((docker-user))
    password: ((docker-passwd))

- name: kube-deploy
  type: kubernetes
  source:
    server: https://IP:8443
    namespace: default
    token: tokenvalue
    insecure_skip_tls_verify: true
    #certificate_authority: ((ca-crt))

jobs:
- name: adservice
  plan:
  - get: git-repo
    trigger: true
  - task: tag docker build
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: katochm/docker-test
          tag: alpine-git
          username: ((docker-user))
          password: ((docker-passwd))
      inputs:
      - name: git-repo
      outputs:
      - name: tags
      run: 
        path: /bin/sh
        args:
        - -exc
        - |
          cd git-repo/
          export GIT_SHA=$(git rev-parse HEAD)
          echo $GIT_SHA
          cd ..
          echo $GIT_SHA > tags/short-hash-commit
      #    cp /tmp/build/0f7a9e8e/git-repo/docs/short-hash-commit /tmp/build/0f7a9e8e/docs/short-hash-commit
          
  - put: docker-hub
    params:
      tag: tags/short-hash-commit
      #tag_as_latest: true
      build: git-repo/src/adservice
- name: deploy-application
  plan:
  - get: docker-hub
    trigger: true
  - get: git-repo
  - task: attach short-hash-commit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: katochm/docker-test
          tag: alpine-git
          username: ((docker-user))
          password: ((docker-passwd))
      inputs:
      - name: git-repo
      outputs:
      - name: adservice 
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          cd git-repo/kubernetes-manifests
          export GIT_SHA=$(git rev-parse HEAD)
          echo $GIT_SHA
          export value=katochm/adservice
          echo $value
          sed -i "s+latest+$value:$GIT_SHA+g" adservice.yaml
          cp adservice.yaml ../../adservice/

  - put: kube-deploy
    params:
      kubectl: apply -f adservice/adservice.yaml 
      #kubectl: delete pods -l app=adservice
